# Generated by Django 2.2.4 on 2019-08-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roman_to_arabic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='roman',
        ),
    ]
