# Generated by Django 2.2.4 on 2019-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roman_to_arabic', '0002_remove_number_roman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roman', models.CharField(max_length=200)),
                ('arabic', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
